name: Docker

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      PLATFORMS: linux/amd64,linux/arm64,linux/arm64/v8

    strategy:
      fail-fast: false
      matrix:
        version:
        - "1.7.8"
        bq_version:
        - "1.7.4"
        ch_version:
        - "1.7.2"
        base:
        - python:3.11.8-slim-bookworm
        - python:3.12.2-slim-bookworm
        include:
        - base: python:3.11.8-slim-bookworm
          base-name: py3.11-bookworm
        - base: python:3.12.2-slim-bookworm
          base-name: py3.12-bookworm
          is-latest-base: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      id: config
      env:
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      run: |-
        NPROC=$(nproc)

        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_ENV
        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_OUTPUT

        echo "image-owner=${GITHUB_REPOSITORY_OWNER}" >> $GITHUB_OUTPUT
        echo "image-name=${GITHUB_REPOSITORY_NAME#docker-}" >> $GITHUB_OUTPUT

    - name: Setup - QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ env.PLATFORMS }}

    - name: Setup - Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup - Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |-
          ${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
          ghcr.io/${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
        flavor:
          latest=false
        tags: |-
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }},suffix=-${{ matrix.base-name }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.version }},suffix=-${{ matrix.base-name }}
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.version }}

    - name: Build
      uses: docker/build-push-action@v5
      id: build
      with:
        context: .
        build-args: |
          base=${{ matrix.base }}
          version=${{ matrix.version }}
          bq_version=${{ matrix.bq_version }}
          ch_version=${{ matrix.ch_version }}
        push: true
        platforms: ${{ env.PLATFORMS }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
